CADC-8571 - change getPermissionsAction to use query parameters
opencadc/caom2db pull request #214
Opened 2020-10-30 23:15 UTC by jburke-cadc

2020-11-02 20:21 UTC, pdowler requested changes
Missing authorize request to configured identities (maybe groups) only. 

Missing OP parameter as required by API (same API as baldur)

2020-11-06 22:17 UTC, pdowler requested changes

2020-11-06 22:17 UTC, pdowler commented on caom2-repo-server/src/main/java/ca/nrc/cadc/caom2/repo/PropertiesAuthorization.java
> +                if (!groupClient.isMember(groupURI)) {
The logic here is flawed. This converting isMember==false into an AccessControlException which means using exceptions for code logic, not just failures. 

In practice, up in isAuthorizedGroup that calls this action, the first false  looks like it will  be fatal -- so in fact the caller has to belong to all the groups. That's a great example of why using exceptions for logic is soooo bad.

And to be clear - it doesn't really matter if this happens to work correctly because I can't really tell what it will do.

2020-11-06 22:17 UTC, pdowler commented on caom2-repo-server/src/main/java/ca/nrc/cadc/caom2/repo/PropertiesAuthorization.java
> +        // Check if calling user is a member of a properties file group.
look at the group permission  check in PermissionsCheck line ~151 (cadc-inventory-util: no child methods, no gratuitous extra Subject.doAs... and the comment suggests when one might want to use isMember() rather than getMemberships()

2020-11-09 22:24 UTC, jburke-cadc commented on caom2-repo-server/src/main/java/ca/nrc/cadc/caom2/repo/PropertiesAuthorization.java
> +public class PropertiesAuthorization {
Renamed to PropertyAuthorizer.

2020-11-09 22:31 UTC, jburke-cadc commented on caom2-repo-server/src/main/java/ca/nrc/cadc/caom2/repo/PropertiesAuthorization.java
> +
Which was my first choice, except that the LogControlServlet used users and groups in the properties file, and was thinking of a common use class and having to change existing properties files. But should use the proper name. Updated to user and group.

2020-11-09 22:34 UTC, jburke-cadc commented on caom2-repo-server/src/main/java/ca/nrc/cadc/caom2/repo/PropertiesAuthorization.java
> +    public void authorize(final Subject subject, final String propertiesFilename, boolean denyAccessWithoutConfig)
Removed the Subject and flag from the method call. The filename is only used by the PropertiesReader, a File is never used. Moved the filename to the constructor.

2020-11-09 22:44 UTC, jburke-cadc commented on caom2-repo-server/src/main/java/ca/nrc/cadc/caom2/repo/PropertiesAuthorization.java
> +        // Check if calling user is a member of a properties file group.
Followed the PermissionsCheck pattern for group checking, much cleaner and simpler. I would guess there would be one, and at most two, groups configured, and did use isMember().

2020-11-17 14:12 UTC, pdowler requested changes

2020-11-17 14:12 UTC, pdowler commented on caom2-repo-server/src/main/java/ca/nrc/cadc/caom2/repo/PropertyAuthorizer.java
> +            throw new ResourceNotFoundException("Properties file " + propertiesFilename + " not found or cannot be read");
When used inside a web service, if the ResourceNotFoundException here is not handled by the calling code this is going to turn into a 404 to the user. At least it is a checked exception but actions (cadc-rest) can throw anything so the compiler isn't going to help people get this right.  If/when we pull this out to a library that won't be great. Well, let's see how it is used...

2020-11-17 14:12 UTC, pdowler commented on caom2-repo-server/src/main/java/ca/nrc/cadc/caom2/repo/action/GetPermissionsAction.java
> +        propertiesAuthorization.authorize();
Yeah: not catching the ResourceNotFoundException here means the caller will get a 404 if the file is missing. That's bad but prett much what I expected because `doAction() throws Exception`. So, either RNFE needs to be caught here and turned into an exception that produces the right response or the authorizer should really throw the right thing.

2020-11-18 23:40 UTC, jburke-cadc commented on caom2-repo-server/src/main/java/ca/nrc/cadc/caom2/repo/action/GetPermissionsAction.java
> +        propertiesAuthorization.authorize();
Updated the PropertyAuthorizer to throw an AccessControlException instead of the ResourceNotFoundException.

2020-11-18 23:41 UTC, jburke-cadc commented on caom2-repo-server/src/main/java/ca/nrc/cadc/caom2/repo/PropertyAuthorizer.java
> +            throw new ResourceNotFoundException("Properties file " + propertiesFilename + " not found or cannot be read");
See the next comment.

2020-11-20 18:38 UTC, pdowler requested changes

2020-11-20 18:38 UTC, pdowler commented on caom2-repo-server/src/main/java/ca/nrc/cadc/caom2/repo/PropertyAuthorizer.java
> +            throw new AccessControlException("Properties file " + propertiesFilename + " not found or cannot be read");
This is leaking useless internal information to clients. The message should just be something short like "no grants configured".

2020-11-20 18:38 UTC, pdowler commented on caom2-repo-server/src/main/java/ca/nrc/cadc/caom2/repo/PropertyAuthorizer.java
> +                        log.info("authorized group: " + authorizedGroupURI);
no info level log messages in web services other than the machine readable START and END messages.

2020-11-20 18:38 UTC, pdowler commented on caom2-repo-server/src/main/java/ca/nrc/cadc/caom2/repo/PropertyAuthorizer.java
> +        throw new AccessControlException("User and group authorization failed.");
There are two ways to get to this line: 
* CredUtil.checkCredrentials() returns false
* user does not belong to any groups 
Neither is a failure and an AccessControlException is not a failure, it is a denial. If the 
```
if (CredUtil.checkCredrentials()) {

}
```
had an `else` clause, it could throw an AccessControlException with a correct and useful message for that case. Since the "allowed" is done via immediate return, the throw at the end is the normal successful denial and should be
```
throw new AccessControlException("permission denied");
```
No reason needed.

Aside: At some point I want to move the "permission denied" string into the exception handler because code is currently and always going to be inconsistent in that prefix message - so in future this would throw with no message, but not now.

2020-11-20 21:12 UTC, jburke-cadc commented on caom2-repo-server/src/main/java/ca/nrc/cadc/caom2/repo/PropertyAuthorizer.java
> +            throw new AccessControlException("Properties file " + propertiesFilename + " not found or cannot be read");
Updated the exception message.

2020-11-20 21:14 UTC, jburke-cadc commented on caom2-repo-server/src/main/java/ca/nrc/cadc/caom2/repo/PropertyAuthorizer.java
> +                        log.info("authorized group: " + authorizedGroupURI);
Changed info level logging to debug.

2020-11-20 21:20 UTC, jburke-cadc commented on caom2-repo-server/src/main/java/ca/nrc/cadc/caom2/repo/PropertyAuthorizer.java
> +        throw new AccessControlException("User and group authorization failed.");
Adding the else does allow a useful message to the client. Updated the final exception message.

2020-11-24 17:49 UTC, pdowler approved these changes

2020-11-24 17:50 UTC, merged