Cadc 9186 Improve on error messages
opencadc/caom2db pull request #225
Opened 2021-03-11 19:44 UTC by yeunga

Pulled in the changes from CADC-8575 and CADC-8891 so that testing could be done using Storage Inventory.

2021-03-12 22:06 UTC, jburke-cadc submitted a review, later dismissed

2021-03-22 20:08 UTC, pdowler requested changes
The Util.addToSkipTable(...) method usage (ArtifactHarvester line 285) and the implementation is really "update this skip record and tell me if anything changed so I can persist". The name is bad: it doesn't "addToSkipTable". But more: what it really does is a bad plan and not really consistent with other usage of the db lib.

A better plan is to simply update the HarvestSkipURI record and always call harvestSkipURIDAO.put(...) and let the DAO class worry about optimising the put (eg avoiding database operation if there is no material change). aside: currently the DAO is not optimised to avoid the database op, but that's OK. 

Then the only catch is making sure to handle these update scenarios when the skip record exists:

(1) policy is PUBLIC_ONLY
releaseDate is (now) null: delete the HarvestSkipURI record if necessary

(2) policy is PUBLIC_ONLY
ArtifactHarvester.PROPRIETARY.equals(skip.errorMessage) aka "was proprietary" **or**
ArtifactHarvester.PROPRIETARY.equals(this.errorMessage) aka "is proprietary": assign skip.tryAfter and skip.errorMessage

I think you can cleanly implement this inline in ArtifactHarvester and don't need a Util class.

2021-04-01 22:51 UTC, pdowler requested changes

2021-04-01 22:51 UTC, pdowler commented on caom2-artifact-sync/src/main/java/ca/nrc/cadc/caom2/artifactsync/ArtifactHarvester.java
> +                                            if (ArtifactHarvester.PROPRIETARY == skip.errorMessage || ArtifactHarvester.PROPRIETARY == this.errorMessage) {
You need to use `equals(...)` instead of `==` for these string comparisons. The string value in the HarvestSkipURI record has to be assumed to be a different object (it's a string, nit an enum).

Also, I don't think the `addToSkip` boolean and `if (addToSkip)` check do anything: once you are inside this code block you are always end up calling `dao.put(...)`... could be simplified.

same in ArtifactValidator

2021-04-06 18:23 UTC, pdowler approved these changes

2021-04-06 18:23 UTC, merged