CADC-8575 CADC-9186 Updated artifact-discover and artifact-validate r…
opencadc/caom2db pull request #230
Opened 2021-05-25 23:37 UTC by yeunga

…eporting.

Since we now update the harvestskipuri table, we should differentiate between adding and updating the harvestskipuri table. 

Example artifact-discover output:
2021-05-25 14:52:52.228 [Thread-1] INFO  ArtifactHarvester  - ENDDISCOVER: {"total":"120","added":"0","updated":"0","time":"38751","date":"2021-05-25 21:52:13.477"}

Example artifact-validate summary outputs:{"logType":"summary","collection":"IRIS","totalInCAOM":"2580","totalInStorage":"42","totalCorrect":"42","totalDiffChecksum":"0","totalDiffLength":"0","totalDiffType":"0","totalNotInCAOM":"0","totalMissingFromStorage":"2538","totalNotPublic":"0","totalAlreadyInSkipURI":"0","totalNewSkipURI":"0","totalUpdateSkipURI":"2538","time":"30572"}
{"logType":"summary","collection":"IRIS","totalInCAOM":"2580","totalInStorage":"42","totalCorrect":"42","totalDiffChecksum":"0","totalDiffLength":"0","totalDiffType":"0","totalNotInCAOM":"0","totalMissingFromStorage":"2538","totalNotPublic":"0","totalAlreadyInSkipURI":"0","totalNewSkipURI":"2538","totalUpdateSkipURI":"0","time":"30124"}

2021-05-26 18:23 UTC, andamian approved these changes

2021-05-26 18:23 UTC, andamian commented on caom2-artifact-sync/src/main/java/ca/nrc/cadc/caom2/artifactsync/DownloadArtifactFiles.java
> +import ca.nrc.cadc.net.TransientException;
Is this used anywhere?

2021-05-26 18:43 UTC, yeunga commented on caom2-artifact-sync/src/main/java/ca/nrc/cadc/caom2/artifactsync/DownloadArtifactFiles.java
> +import ca.nrc.cadc.net.TransientException;
Good catch. Removed.

2021-05-31 17:25 UTC, pdowler requested changes
From the example log messages:
```
"totalAlreadyInSkipURI":"0","totalNewSkipURI":"0","totalUpdateSkipURI":"2538"
"totalAlreadyInSkipURI":"0","totalNewSkipURI":"2538","totalUpdateSkipURI":"0"
```
From the first line, weren't the updated records already in the skip table? So totalAlreadyInSkipURI is clearly not a count of total skip records before or after... it's really a count of the subset of existing skip records that were looked at but not modified? That's pretty subtle and will be confusing.

In caom2harvester --validate mode, the summary report has 4 numbers (counts):
```
total + " mismatches: " + mismatch + " known: " + known + " new: " + added;
```
(total is number of observations examined, less interesting). `mismatches` is the total number of skip records. This mode does update skip records, but it doesn't distinguish that it updated the (already) known records. It should always be true that `mismatch == known + added` or it is confusing (sign of bug). When I look at that and I look at totalAlreadyInSkipURI the latter isn't very clear to me: it sounds like it is the total number of skip records but it isn't. You could report skips,updated,new where skips == updated + new... the label style is fine but the meanings have to be clear and some fields adding up to another always helps people understand.

2021-05-31 21:59 UTC, yeunga commented
artifact-validate summary now looks this:{"logType":"summary","collection":"IRIS","totalInCAOM":"2580","totalInStorage":"16","totalCorrect":"0","totalDiffChecksum":"0","totalDiffLength":"0","totalDiffType":"0","totalNotInCAOM":"16","totalMissingFromStorage":"2580","totalNotPublic":"0","totalInSkipURI":"2580","totalNewSkipURI":"0","totalUpdateSkipURI":"2580","time":"28364"}

2021-06-01 16:11 UTC, pdowler approved these changes

2021-06-01 16:11 UTC, merged