CSD-1567 Replaced deprecated HttpDownload with HttpGet and added time…
opencadc/caom2db pull request #239
Opened 2021-11-24 18:51 UTC by yeunga

…outs to avoid HttpGet being 'hung'.

Asked Ling to try out artifact-diff-si and artifact-download-si on sciproc2-01 using HST collection. artifact-diff-si completed without being 'hung' and artifact-download-si uploaded more than 250 files to storage inventory without being 'hung' as well.

2021-11-25 18:47 UTC, pdowler requested changes

2021-11-25 18:47 UTC, pdowler commented on caom2-artifact-sync/src/main/java/ca/nrc/cadc/caom2/artifactsync/ArtifactValidator.java
> +            get.prepare();
You don't normally need to call prepare() and run(). The latter calls prepare(), rteads the response , and captures all exceptions. The usual pattern is either this:
```
try {
   get.prepare();
   InputStream istream = get.getInputStream();
   ...
} catch ...
```
or this:
```
get.run();
if (get.Throwable() != null) {
   ...
```

The explicit prepare/getInputStream is recent and allows for better exception handling and simpler reading, but I would not bother changing style in caom2-artifact-sync at this point.

2021-11-25 18:47 UTC, pdowler commented on caom2-artifact-sync/src/main/java/ca/nrc/cadc/caom2/artifactsync/DownloadArtifactFiles.java
> +                head.prepare();
as above: don't need explicit prepare()

2021-11-26 17:27 UTC, yeunga commented on caom2-artifact-sync/src/main/java/ca/nrc/cadc/caom2/artifactsync/ArtifactValidator.java
> +            get.prepare();
Removed prepare().

2021-11-26 17:28 UTC, yeunga commented on caom2-artifact-sync/src/main/java/ca/nrc/cadc/caom2/artifactsync/DownloadArtifactFiles.java
> +                head.prepare();
Removed prepare().

2021-11-29 22:00 UTC, pdowler approved these changes

2021-11-29 22:00 UTC, merged