cadc-11115 new caom2-meta-sync module
opencadc/caom2db pull request #247
Opened 2022-05-05 17:37 UTC by jburke-cadc

2022-05-05 21:48 UTC, pdowler requested changes
Haven't looked at Main yet; config/doc changes first and that will reduce what's in Main

2022-05-05 21:48 UTC, pdowler commented on caom2-meta-sync/README.md
> +# Destination caom2 database settings
server/database will requrie a ~/.dbrc file - for containers we want it all right here, so: schema, username, password, url. The database name is in the jdbc URL and we don't actually need it in the code since postgresql doesn't support cross-database statements. Pretty sure it's safe to leave it null in the caom2persistence library usage if it is there.

2022-05-05 21:48 UTC, pdowler commented on caom2-meta-sync/README.md
> +
Let's remove the rest of these: dryrun, minDate, maxDate, nochecksum. Not useful.

2022-05-05 21:48 UTC, pdowler commented on caom2-meta-sync/README.md
> +### cadcproxy.pem
Make it clear that cadcproxy.pem is optional and running anon is a supported option.

2022-05-05 21:48 UTC, pdowler commented on caom2-meta-sync/README.md
> +### .dbrc
No .dbrc

2022-05-05 21:48 UTC, pdowler commented on caom2-meta-sync/README.md
> +
I assume this runs to completion and then exits (unchanged from current behaviour). That should be documented here because it is different from from how SI applications work. In future, we might make this run indefinitely, but that may require other changes.

2022-05-05 21:48 UTC, pdowler commented on caom2-meta-sync/build.gradle
> +description = 'OpenCADC CAOM MetaData Sync application'
MetaData -> Metadata (not CamelCase)

2022-05-05 21:48 UTC, pdowler commented on caom2-meta-sync/build.gradle
> +applicationDefaultJvmArgs = ['-Xms2048m','-Xmx8192m','-XX:OnOutOfMemoryError="kill -3 %p"']
Remove jvm args from build -- this overlaps what the cadc-java image has so if we need to tweak these it will need to be done/supported by the base image

2022-05-05 21:48 UTC, pdowler commented on caom2-meta-sync/build.gradle
> +distributions {
the extra script can be ignored for now so remove this block as well.

2022-05-06 14:44 UTC, jburke-cadc commented on caom2-meta-sync/README.md
> +
Removed the above properties.

2022-05-06 14:58 UTC, jburke-cadc commented on caom2-meta-sync/README.md
> +# Destination caom2 database settings
I had the server and database as separate properties because the method called from Main(), CaomHarvester, takes a HarvestResource for the source and destination. A HarvestResource contains the server, database, schema, and collection. It's not CaomHarvester that uses the server and database to pull the username and password from the .dbrc. That happens in two classes called by CaomHarvester; ObservationHarvester and DeletionHarvester. 
It will take some work to make caom2harvester a library where the Main methods do all the setup work and pass to the library either a DAO or client.

2022-05-06 15:11 UTC, jburke-cadc commented on caom2-meta-sync/README.md
> +### cadcproxy.pem
Updated the readme.

2022-05-06 15:12 UTC, jburke-cadc commented on caom2-meta-sync/README.md
> +### .dbrc
Removed the .dbrc text.

2022-05-06 15:50 UTC, jburke-cadc commented on caom2-meta-sync/README.md
> +
Yes it runs until source queries return no results. Updated the readme.

2022-05-06 15:51 UTC, jburke-cadc commented on caom2-meta-sync/build.gradle
> +applicationDefaultJvmArgs = ['-Xms2048m','-Xmx8192m','-XX:OnOutOfMemoryError="kill -3 %p"']
Removed the line from the build.

2022-05-06 15:51 UTC, jburke-cadc commented on caom2-meta-sync/build.gradle
> +distributions {
Removed.

2022-05-06 17:09 UTC, pdowler commented on caom2-meta-sync/README.md
> +# Destination caom2 database settings
hmmm, there is also no reliable way for the deployer to put a .dbrc file into $HOME in the container since the location of $HOME is an internal implementation detail. I need to think about that, but if we were writing this from scratch we wouldn't use dbrc at all so I'm not inclined to making $HOME in cadc-java a reliable/known/advertised location.

It might be that we need to rewrite more code to containerise this than expected, which probably means forking it. **Let's put this on hold for now...** the work I'm doing on fenwick and a later story on fenwick+ratik will probably shed some light on how to do this.

2023-06-09 20:08 UTC, pdowler requested changes
README and configuration:

Until we get a response from Job on the db, let's simplify as much as possible:


1. get rid of dryrun - it's useless
2. change runContinuously to exitWhenComplete, make it optional, and default to false: that way run forever is the normal mode and this is an exception for special cases
3. both `threads` and `batchSize` are implementation details that we unfortunately expose to operators and explaining sensible values will be very hard... let's make those internal and for now hard code to batchSize=100 and nthreads=batchSize/10.
4. change maxSleep to maxIdle and keep it with the "source" config items
5. hide (remove?) the "source db" config documentation for now
6. use `org.opencadc.caom2.metasync.repoService` for source config, move the `org.opencadc.caom2.metasync.collection` up beside the repoService and make it clear that multiple values are allowed; put all "source:" config before "destination" config
7. use `org.opencadc.caom2.metasync.db.*` for destination config; keep `org.opencadc.caom2.metasync.basePublisherID` with destination config

Style: In the text that explains each config property, you don't need to write out the whole property. It's hard to read... see fenwick (`trackSiteLocations`) or tantar (_buckets_) for two styles that seem to be sufficient ref to the config spec and more readable (just inconsistent, but I think I prefer the italics since they aren't literally exact).

2023-06-15 20:46 UTC, pdowler approved these changes

2023-06-15 20:46 UTC, merged