cadc-11113 caom2-artifact-download scalability
opencadc/caom2db pull request #252
Opened 2022-07-06 13:03 UTC by jburke-cadc

2022-07-15 20:08 UTC, jburke-cadc commented
I wasn't looking at how critwall was doing the sync, since it's a different process than artifact-download. Critwall loops over the transfer urls from raven until a sync succeeds. Once the list of transfer urls is exhausted the sync fails.
artifact-download puts to a single artifactStore. If a sync fails it is retried after `--retryHours` if specified, or after the default retry period. We could add a retry(s) if there is a transient error at any step during the sync process in artifact-download, rather than wait for the next sync attempt after retry period.

2022-07-15 20:40 UTC, jburke-cadc commented
Error handling in artifact-download is rather coarse wrapping the sync in a try and catching a throwable. Critwall is more fine-grained, giving better logging messages about the error that occurred. I'll update download to do the same.

2022-07-18 21:08 UTC, pdowler commented
I would think about this vs critwall as :
1. StorageResolver always generates 1 URL instead of N from transfer negotiation
2. output to an ArtifactStore instead of StorageAdapter

but conceptually and structurally the same

2022-07-26 18:04 UTC, pdowler requested changes

2022-07-27 16:57 UTC, jburke-cadc commented on caom2-artifact-download/README.md
> +# Hours after failed downloads should be retried (default: 6)
I should have deleted profile in the README since I removed profiling from the code.

2022-07-27 17:00 UTC, jburke-cadc commented on caom2-artifact-download/src/intTest/java/org/opencadc/caom2/download/TestUtil.java
> +    public static final String CERTIFICATE_FILE_LOCATION = USER_HOME + "/.ssl/cadcproxy.pem";
Cleaned up the int-tests and simplified the setup, some of which was unnecessary. The only config files needed are for the ArtifactStore, and they are fairly generic, so they are copied from a int-test resource directory into a tmp user.home config directory.

2022-07-27 17:01 UTC, jburke-cadc commented on caom2-artifact-download/src/main/java/org/opencadc/caom2/download/FileSync.java
> +                        harvestSkipURIDAO.iterator(null, null, bucketPrefix, this.retryAfter)) {
Okay, passing in the Artifact class name into the HarvestSkipURI query.

2022-07-27 17:02 UTC, jburke-cadc commented on caom2-artifact-download/src/main/java/org/opencadc/caom2/download/FileSync.java
> +                                new FileSyncJob(harvestSkipURI, this.jobHarvestSkipURIDAO, this.artifactDAO,
Fixed the .this usage.

2022-07-27 17:03 UTC, jburke-cadc commented on caom2-artifact-download/src/main/java/org/opencadc/caom2/download/FileSyncJob.java
> +                msg = "ArtifactResolver error resolving artifact uri";
Fixed the error message, and banished all ArtifactResolver usage.

2022-07-27 17:06 UTC, jburke-cadc commented on caom2-artifact-download/src/main/java/org/opencadc/caom2/download/FileSyncJob.java
> +    public static final int DEFAULT_TIMEOUT = 600000;  // 10 minutes
Updated the timeouts, and use separate connection and read timeouts.

2022-07-27 19:47 UTC, merged