Initial version of support for large files in SI Artifact Store (CADC-11644)
opencadc/caom2db pull request #258
Opened 2022-07-26 23:50 UTC by andamian

2022-07-27 16:45 UTC, pdowler requested changes

2022-07-27 16:45 UTC, pdowler commented on caom2-artifact-store-si/src/main/java/ca/nrc/cadc/caom2/artifactsync/InventoryClient.java
> +            if (ex instanceof TransientException ||
Don't like to see instanceof in exception handling. Best is to not have a generic catch at all and only catch exceptions you can dom something about. Secoind best, if you really need a catch-all, is to put a multicatch of these types before the other catch and rethrow from there.

I'd really like to get rid of wrap;ping in RuntimeException. It makes it hard to unwrap and report the right error message farther up the call sequence. 

Also, you need to abort the txn, preferrably  in a finally clause if the try block doesn't complete.

2022-07-27 16:45 UTC, pdowler commented on caom2-artifact-store-si/src/main/java/ca/nrc/cadc/caom2/artifactsync/InventoryClient.java
> +        httpOp.run();
This can call `prepare()` instead of `run()` and then benefit from the declared exceptions thrown directly rather than captured. iirc, the upload actually happens automatically in the prepare() because that runs until the response (code and headers) are received.

2022-07-27 21:53 UTC, andamian commented on caom2-artifact-store-si/src/main/java/ca/nrc/cadc/caom2/artifactsync/InventoryClient.java
> +        httpOp.run();
Done

2022-11-21 22:59 UTC, pdowler approved these changes

2022-11-21 22:59 UTC, merged