CADC-11778 do a HEAD request to raven for Artifact metadata instead of a luskan query
opencadc/caom2db pull request #262
Opened 2022-10-14 18:09 UTC by jburke-cadc

2022-10-14 19:52 UTC, pdowler requested changes

2022-10-14 19:52 UTC, pdowler commented on caom2-artifact-store-si/src/main/java/ca/nrc/cadc/caom2/artifactsync/InventoryArtifactStore.java
> +            ArtifactMetadata artifactMetadata = new ArtifactMetadata(artifactURI, head.getContentMD5());
This use of `head.getContentMD5()` is sketchy. We used to deliver plain hex md5 via the content-md5 header, which was compliant with http spec. SI services only deliver the digest header and head.getDigest() would return a URI of the form used in inventory and caom2.... 

except, ArtifactMetadata has `String checksum` so it's impossible to know immediately what value to put there. 

I think it would be all around better if ArtifactMetadata used `URI checksum` but I don't know the impact of that change. Can you investigate the impact? 

At a minimum, you need to use `head.getDigest()` and figure out what string to use in that ctor.

2022-10-14 19:52 UTC, pdowler commented on caom2-artifact-store-si/src/main/java/ca/nrc/cadc/caom2/artifactsync/InventoryArtifactStore.java
> +            // return null metadata
please add immediate `return null;` here

2022-10-14 19:52 UTC, pdowler commented on caom2-artifact-store-si/src/main/java/ca/nrc/cadc/caom2/artifactsync/InventoryArtifactStore.java
> +        head.setReadTimeout(5000);
setConnectionTimeout(??)

I usually use 6000 (6 seconds) because that's the length of one  round in D&D, but 5 sec is ok

2022-10-14 20:05 UTC, jburke-cadc commented on caom2-artifact-store-si/src/main/java/ca/nrc/cadc/caom2/artifactsync/InventoryArtifactStore.java
> +            ArtifactMetadata artifactMetadata = new ArtifactMetadata(artifactURI, head.getContentMD5());
I'll have a look at changing the checksum type in ArtifactMetadata.

2022-10-14 20:05 UTC, jburke-cadc commented on caom2-artifact-store-si/src/main/java/ca/nrc/cadc/caom2/artifactsync/InventoryArtifactStore.java
> +            // return null metadata
Done

2022-10-14 20:10 UTC, jburke-cadc commented on caom2-artifact-store-si/src/main/java/ca/nrc/cadc/caom2/artifactsync/InventoryArtifactStore.java
> +        head.setReadTimeout(5000);
The luskan query timeout was 10 seconds, so halved that to get 5 secs. Added setConnectionTimeout.

2022-10-14 21:33 UTC, jburke-cadc commented on caom2-artifact-store-si/src/main/java/ca/nrc/cadc/caom2/artifactsync/InventoryArtifactStore.java
> +            ArtifactMetadata artifactMetadata = new ArtifactMetadata(artifactURI, head.getContentMD5());
Updated to use the header digest as the content checksum.

2022-10-17 17:22 UTC, pdowler approved these changes

2022-10-17 17:22 UTC, merged