CADC-12390 sc2repo README
opencadc/caom2db pull request #272
Opened 2023-06-27 20:55 UTC by jburke-cadc

2023-06-27 22:35 UTC, pdowler requested changes

2023-06-27 22:35 UTC, pdowler commented on sc2repo/README.md
> +sc2repo.test.maxActive={max connections for test admin pool}
one pool - don't need separate test pool

configure as `org.opencadc.torkeep.caom2.maxActive` etc. This would be consistent with the SI config style

2023-06-27 22:35 UTC, pdowler commented on sc2repo/README.md
> +The `admin` account owns and manages (create, alter, drop) sandbox database objects and manages all the content (insert, update, delete).
refer to this as the _caom2_ pool

2023-06-27 22:35 UTC, pdowler commented on sc2repo/README.md
> +### LocalAuthority.properties
LocalAuthority.properties is obsolete; include the standard section about cadc-registry.properties instead

2023-06-27 22:35 UTC, pdowler commented on sc2repo/README.md
> +# required properties
**required props:**
schema (single)
basePublisherID (single)

**optional props:**
readOnlyGroup (multiple)
readWriteGroup (multiple)
computeMetadata (single)

**uncertain**
these are for read-access generation (used by sc2 deployment)
operatorGroup (single)
staffGroup (single)
proposalGroup (single) requires an extended GMS client API to create or modify groups so cannot be implemented with the IvoaGroupClient (not used in current sc2 deployment); these are all connected to the CaomReadAccessGenerator from the caom2-access-control library... probably leave it out for now

**not needed:**
the rest of the old required props can be hard coded if needed, but some should not be needed:

artifactPattern is for finding the right pool (database) for an artifact in the GetPermissionAction, but we have only one pool so it is not needed.

computeMetadataValidation was used before regular validation became good enough (obsolete).

altPattern was for AD->SI migration (obsolete).

2023-06-28 17:33 UTC, jburke-cadc commented on sc2repo/README.md
> +# sc2repo
Updated to use torkeep

2023-06-28 17:34 UTC, jburke-cadc commented on sc2repo/README.md
> +# required properties
Updated the properties.

2023-06-29 20:35 UTC, pdowler commented on sc2repo/README.md
> +# required properties
changing my mind slightly here:

Since schema is not effectively configurable because of tap service limitations, so lets leave that out.

We do need an {entry name}.anon property (optional) to enable anon read/sync.

In baldur we had {entry name}.pattern to match artifact URIs, but here I guess it is subtle but I think we are expecting {entry name} to be {collection}:

Should it really be this:
```
org.opencadc.torkeep.entry = {entry name}
{entry name}.collection = {CAOM collection name}
{entry name}.basePublisherID = {URI}
...
```
Or should it be this?
```
org.opencadc.torkeep.collection = {CAOM collection name}
{collection name}.basePublisherID = {uri}
...
```
One would in principle allow for multiple collections in an entry (I think we still block that in code) but be closer to baldur style and the other would be explicitly one entry per collection.

2023-06-29 20:50 UTC, jburke-cadc commented on sc2repo/README.md
> +# required properties
Either way one could unintentionally configuration a collection twice, and the code should detect and return an error saying so. For the first you'd have to check for dups both for .entry and .collection, the second only .collection. It's a toss up to me, but I'd vote for consistency over the briefer syntax.

2023-07-05 18:15 UTC, pdowler commented on sc2repo/README.md
> +The `admin` account owns and manages (create, alter, drop) sandbox database objects and manages all the content (insert, update, delete).
the `admin` in the text doesn't really map to anything in the template config above. You could add the word "admin" to the place that says "username" above, or change "admin" to something else.

2023-07-13 18:58 UTC, jburke-cadc commented on torkeep/src/main/webapp/index.html
> +  <title>sc2repo API</title>
Copied over the web app files, then forgot about updating them. Updated.

2023-07-13 18:58 UTC, jburke-cadc commented on torkeep/src/main/java/org/opencadc/torkeep/CollectionsConfig.java
> +public class CollectionsConfig {
That makes better sense, renamed.

2023-07-13 19:02 UTC, jburke-cadc commented on torkeep/README.md
> +CAOM repository service for the CADC data engineering sandbox.
Updated the README for the comments below.

2023-07-17 23:35 UTC, pdowler approved these changes

2023-07-17 23:35 UTC, merged